ANY_SYNC_BUNDLE_INIT_FILENODE_DEFAULT_LIMIT: ENC[AES256_GCM,data:cMMAVgiSItHxoRxfIA==,iv:LDkXV9HP8fPfl7gf6jEO9u57/1+uaFed7sXaRLjOktc=,tag:Bt43xFA/lwuvAUPI7D0e3Q==,type:str]
sops:
    age:
        - recipient: age192e44wu72gmpuag6zvdmnh6f9r4w63zyyyjajszqepeyhr440ynsjyvgaf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdmZrOHRMT2xZT0FMQTh5
            cklDWDlsWGg2cmlvWW4xY0tmYk91Wk5aUjJZCmdpMlhkdFVYb2RZUlhPSGlFV0c2
            WmtlV2NRODF0RnBsWEZyRjZoMDlpZ00KLS0tIGxJb3VydTJTYlk4QVQ1cW1ONGF6
            NkpXV1g5c0xxQkdMMlN2MXNaTUc4dzQKr/rk0c7YLWTCcZU+zAOM6W94+sURIt4P
            7Guawt1Mbnek45/n6aFjHpo07nvlzq8pNfBcsnac1v4ANPq5qeRIGQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n777d4keln02xdeq93337uze3l24wcyayuhdv7a860ykqv35cejsp9rd0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbElKZFNhRGpJbEpIUEc0
            Q2JUVmZ5QWQ0UnoyQ2o1VEcxdjF2QXlZV1hZCk1mM2lINE9QMHMxTmtpczJoL0Mr
            Vm95cGptTCtFTmR3VEJjblVDQU9iMjgKLS0tIGVleWs0RGhicFA5ejVmZXBhT2E4
            UWovQngyUlVYZGErN09VNExqbzZkOGsKCgjrW9722qiYcdmyRgk0+yGzehqMoWBX
            gVTi98eDg4qOqX12IFyI83h3FUk2vBystAkJmM5tIGg1/otE8XQuXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T11:40:30Z"
    mac: ENC[AES256_GCM,data:s38GX+iUIQ+QCEEAYFAVL46VUNH2kNzYVCcjFHP1QRTebS4ESF9elAFR9teEDJ1s5xLhBi3piP5DrHAjLbllYcl2My/3+39Vn7Vtxz7WSUraZNiiOe4F15ZE2vYHW9dboy3qBm9operi7drRsHeA/Gl1DEK3vb+G+ZRMHdowR3o=,iv:grHlFdKNZSIW3jVZRtsPqmfUbp6Fi7hkcWO0rufdJmU=,tag:FB/WG6i5vJUz2Sfe96GW8w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
